services:
  pointfusion:
    image: pointfusion
    build:
      context: .
      args:
        - USERNAME=${USER}
    environment:
      - DISPLAY=${DISPLAY}
      - USERNAME=${USER}
      - DEBIAN_FRONTEND=noninteractive
      - NVIDIA_VISIBLE_DEVICES=all
      - QT_QPA_PLATFORM=xcb  # Use the xcb plugin
      - QT_X11_NO_MITSHM=1  # Avoid shared memory issues
      - QT_DEBUG_PLUGINS=1
    volumes:
      - ./:/home/${USER}/pointfusion
      - ./datasets:/home/${USER}/pointfusion/datasets
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]