name: pointfusion
channels:
  - defaults
  - pytorch
dependencies:
  - numpy
  - pytorch
  - pillow
  - opencv
  - torchvision
  - matplotlib
  - pip:
    - torchsummary
    - scipy
    - open3d
    - distinctipy