name: pointfusion
channels:
  - pytorch
  - anaconda
  - open3d-admin
  - nvidia
  - eyeware
dependencies:
  - python=3.8
  - numpy
  - pillow
  - opencv
  - matplotlib
  - open3d
  - pip
  - pip:
    - torchsummary
    - scipy
    - distinctipy
    - scikit-learn
    - pandas
    - addict
    - plyfile
    - tqdm
    - torch
    - torchvision
    - torchaudio
    - pyrealsense2
    - pyyaml