name: pointfusion
channels:
  - pytorch
  - anaconda
  - open3d-admin
  - nvidia
  - eyeware
dependencies:
  - python=3.8
  - numpy
  - pillow
  - opencv
  - matplotlib
  - open3d
  - pytorch=*=*cuda*
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch-cuda=11.7
  - pip
  - pip:
    - torchsummary
    - scipy
    - distinctipy
    - scikit-learn
    - pandas
    - addict
    - plyfile
    - tqdm
    - pyrealsense2
    - pyyaml
