[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pointfusion"
description = "A package for point cloud data fusion"
readme = "README.md"
authors = [
    {name = "Mark Robinson", email = "wakrson@gmail.com"},
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "numpy",
    "scipy",
    "open3d"
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/ecmwf-lab/ai-models/"
Repository = "https://github.com/ecmwf-lab/ai-models/"
Issues = "https://github.com/ecmwf-lab/ai-models/issues"

[tool.setuptools.packages.find]
include = ["pointfusion"]

[project.scripts]
trainer = "pointfusion.trainer:main"
